ministryofjustice/hmpps-visits-internal-admin-ui

.circleci/config.yml
README.md
cypress.config.ts
feature.env
integration_tests/e2e/home.cy.ts
integration_tests/e2e/login.cy.ts
integration_tests/e2e/prisons/supportedPrisons.cy.ts
integration_tests/mockApis/prisonRegister.ts
integration_tests/mockApis/visitScheduler.ts
integration_tests/pages/home.ts
integration_tests/pages/index.ts
integration_tests/pages/page.ts
integration_tests/pages/prisons/listSupportedPrisons.ts
integration_tests/pages/prisons/prisonsIndex.ts
package-lock.json
package.json
server/data/visitSchedulerApiTypes.ts
server/routes/index.test.ts
server/routes/prisons/index.test.ts
server/routes/prisons/supportedPrisons.test.ts
server/routes/testutils/appSetup.ts
server/views/pages/index.njk
server/views/pages/prisons/index.njk
server/views/partials/layout.njk

* Add `cheerio` and some example routes tests
* Integration tests
* Add Wiremock config for Prison register and Visit scheduler APIs
* Add some basic, sample integration tests
(These tests are really just to check everything's wired up correctly; they'll need revising once the 'demo' content is replaced with actual features...)

VB-1825 Setting up testing and add some tests

---

assets/scss/local.scss
package-lock.json
package.json
server/routes/prisons/prisons.ts
server/services/prisonService.test.ts
server/utils/nunjucksSetup.test.ts
server/utils/nunjucksSetup.ts
server/views/pages/prisons/prisons.njk
server/views/partials/errorSummary.njk
server/views/partials/layout.njk

Add `express-validator` for validation.
* field validation on text input to add a prison
* check that prison code is actually in prison register before adding

VB-2269 Validate adding a new prison

---

.circleci/config.yml

Uncommented CI config to allow release to pro

Allow deployment to prod

---

server/@types/express/index.d.ts
server/@types/vists-admin.d.ts
server/data/prisonRegisterApiClient.ts
server/data/visitSchedulerApiClient.ts
server/routes/prisons/prisons.test.ts
server/routes/prisons/prisons.ts
server/services/prisonService.ts
server/utils/nunjucksSetup.test.ts
server/utils/nunjucksSetup.ts
server/views/pages/prisons/edit.njk

* Catch and handle error responses from APIs
* Add more unit tests to cover `POST` routes and validation scenarios
* Fix issue where `errorSummary` component would render a link with`undefined` as the `href`, instead of just plain text
* Tidy up some TypeScript to use more explicit types

VB-2309 Handle server error responses

---

.circleci/config.yml

Reverts ministryofjustice/hmpps-visits-internal-admin-ui#25

Revert "Deploy main to dev environment without approval"

---

integration_tests/mockApis/visitScheduler.ts
server/@types/visit-scheduler-api.d.ts
server/data/visitSchedulerApiClient.test.ts
server/data/visitSchedulerApiClient.ts

Update to use new `/admin` prefix on API endpoints.

VB-2320 Updates to Visit scheduler API

---

server/data/visitSchedulerApiClient.test.ts
server/data/visitSchedulerApiClient.ts
server/data/visitSchedulerApiTypes.ts
server/routes/prisons/prisons.ts
server/routes/testutils/testData.ts
server/services/index.ts
server/services/sessionTemplateService.test.ts
server/services/sessionTemplateService.ts
server/services/testutils/mocks.ts

Added a Session Template Service, will be used for all session template api usage.

VB-2320, add sessionTemplateService

---

assets/scss/local.scss
package-lock.json
package.json
server/utils/nunjucksSetup.test.ts
server/utils/nunjucksSetup.ts
server/views/pages/prisons/prisons.njk
server/views/pages/prisons/viewSessionTemplates.njk

* Add `date-fns` module
* Add Nunjucks `formatDate` filter from Staff UI project
* Format templates table
* Fix issues with excessive whitespace
To do:
* add ability to show all / active / inactive session templates
* tests

VB-2320 Format session templates view table

---

server/data/visitSchedulerApiClient.ts
server/routes/prisons/prisons.ts
server/services/sessionTemplateService.ts
server/views/pages/prisons/viewSessionTemplates.njk
server/views/pages/prisons/viewSingleSessionTemplate.njk

Add view specific session page
Requires tests and macro creation for `ul` generation

VB-2263, create single session template page

---

assets/scss/local.scss
server/constants/sessionTemplatesFilterRanges.ts
server/data/visitSchedulerApiClient.test.ts
server/data/visitSchedulerApiClient.ts
server/data/visitSchedulerApiTypes.ts
server/routes/prisons/prisons.test.ts
server/routes/prisons/prisons.ts
server/services/sessionTemplateService.test.ts
server/services/sessionTemplateService.ts
server/views/pages/prisons/viewSessionTemplates.njk

Add button actions (using [MoJ Identity bar component](https://design-patterns.service.justice.gov.uk/components/identity-bar/)) to filter listing of session templates to show all, expired or current/future.
Still to do: add tests!

VB-2320 Add filters for session templates listing

---

.circleci/config.yml

* Deploy `main` to dev environment automatically
* Feature branches can be optionally deployed to dev and staging

CircleCI - auto deploy main to dev

---

docker-compose.yml

Rename Redis to avoid clashes with other projects.

Rename Redis Docker container

---

integration_tests/e2e/prisons/prisonStatus.cy.ts
integration_tests/mockApis/visitScheduler.ts
server/@types/visit-scheduler-api.d.ts
server/constants/sessionTemplatesFilterRanges.ts
server/routes/prisons/sessionTemplates/sessionTemplatesController.ts
server/routes/prisons/sessionTemplates/singleSessionTemplateController.test.ts
server/routes/testutils/testData.ts
server/views/pages/prisons/addSessionTemplate.njk
server/views/pages/prisons/viewSessionTemplates.njk
server/views/pages/prisons/viewSingleSessionTemplate.njk

Imported visit scheduler changes
biWeekly -> weekly frequency
ACTIVE_OR_FUTURE -> CURRENT_OR_FUTURE (session template filter)
*(Can't run integration tests locally so can't work out what the reported problem is)*

Visit scheduler changes

---

server/data/visitSchedulerApiClient.ts
server/data/visitSchedulerApiTypes.ts
server/routes/prisons/sessionTemplates/addSessionTemplateController.ts
server/routes/prisons/sessionTemplates/index.ts
server/services/sessionTemplateService.ts
server/views/pages/prisons/addSessionTemplate.njk

Added post route to addSessionTemplate, can now create a basic session template
To-do
Unit tests
validation

VB-2322, post route for addSessionTemplate

---

server/constants/daysOfWeek.ts
server/routes/prisons/sessionTemplates/addSessionTemplateController.ts
server/views/pages/prisons/addSessionTemplate.njk

* Fix handling of conditional field for end date
* Set `formValues` in `catch()` block
* Set constant with days of week for re-use across the app

Add session template page - fixes

---

.gitignore
integration_tests/e2e/prisons/viewSessionTemplateStatus.cy.ts
integration_tests/mockApis/visitScheduler.ts
integration_tests/pages/page.ts
integration_tests/pages/prisons/viewSessionTemplate.ts
integration_tests/pages/prisons/viewSessionTemplates.ts
server/data/visitSchedulerApiClient.ts
server/routes/prisons/sessionTemplates/index.ts
server/routes/prisons/sessionTemplates/singleSessionTemplateController.test.ts
server/routes/prisons/sessionTemplates/singleSessionTemplateController.ts
server/routes/testutils/testData.ts
server/services/sessionTemplateService.ts
server/views/pages/prisons/viewSingleSessionTemplate.njk

Added UI code for session template active or inactive.
First go at this,

VB-2383 Front-end session template active true/false

---

server/data/visitSchedulerApiClient.ts
server/routes/prisons/sessionTemplates/addSessionTemplateController.test.ts
server/routes/prisons/sessionTemplates/addSessionTemplateController.ts
server/routes/testutils/testData.ts

* Add test for successful `POST`
* Tweak sanitisation/validation chain - in particular to get `number` types where required

VB-2322 Add session template - tweaks and tests

---

server/data/visitSchedulerApiClient.ts
server/data/visitSchedulerApiTypes.ts
server/routes/prisons/index.ts
server/routes/prisons/locationGroups/index.ts
server/routes/prisons/locationGroups/locationGroupsController.ts
server/services/index.ts
server/services/locationGroupsService.ts
server/views/pages/prisons/locationGroups/viewLocationGroups.njk

Display locations groups for a prison

VB-2408, view location groups

---

server/data/visitSchedulerApiClient.test.ts
server/data/visitSchedulerApiClient.ts
server/data/visitSchedulerApiTypes.ts
server/routes/prisons/categoryGroups/categoryGroupsController.ts
server/routes/prisons/categoryGroups/index.ts
server/routes/prisons/index.ts
server/routes/prisons/locationGroups/index.ts
server/routes/prisons/locationGroups/locationGroupsController.ts
server/routes/testutils/testData.ts
server/services/categoryGroupService.test.ts
server/services/categoryGroupService.ts
server/services/index.ts
server/services/locationGroupService.test.ts
server/services/locationGroupService.ts
server/services/locationGroupsService.ts
server/services/testutils/mocks.ts
server/views/pages/prisons/categoryGroups/viewCategoryGroups.njk

* Add page to list a prison's category groups
* Add some API client and service unit tests
* A few naming tweaks for consistency

VB-2417, VB-2418 Category groups listing page

---

server/@types/visit-scheduler-api.d.ts
server/data/visitSchedulerApiClient.test.ts
server/data/visitSchedulerApiClient.ts
server/data/visitSchedulerApiTypes.ts
server/routes/prisons/incentiveLevelGroups/incentiveLvelGroupsController.ts
server/routes/prisons/incentiveLevelGroups/index.ts
server/routes/prisons/index.ts
server/routes/testutils/testData.ts
server/services/incentiveLevelGroupService.test.ts
server/services/incentiveLevelGroupService.ts
server/services/index.ts
server/services/testutils/mocks.ts
server/views/pages/prisons/incentiveLevelGroups/viewIncentiveLevelGroups.njk

* Add API calls and `IncentiveLevelGroupsService`
* Add routes/controllers for incentive levels
* Build listing page

VB-2436, VB-2437 Incentive level groups listing page

---

server/middleware/setUpWebSecurity.ts

Fix browser error: `Unrecognized Content-Security-Policy directive 'formaction'.`

Fix 'formaction' CSP error

---

helm_deploy/values-staging.yaml

Admin UI staging environment was using the dev visit scheduler 😬 🤦‍♂️

Use staging visit scheduler in staging admin environment

---

assets/scss/local.scss
server/routes/prisons/incentiveGroups/addIncentiveGroupController.ts
server/routes/prisons/locationGroups/addLocationGroupController.test.ts
server/routes/prisons/locationGroups/addLocationGroupController.ts
server/routes/prisons/locationGroups/index.ts
server/routes/prisons/locationGroups/locationGroupsController.ts
server/routes/prisons/locationGroups/singleLocationGroupController.ts
server/views/pages/prisons/incentiveGroups/addIncentiveGroup.njk
server/views/pages/prisons/locationGroups/addLocationGroup.njk
server/views/pages/prisons/locationGroups/viewLocationGroups.njk
server/views/pages/prisons/locationGroups/viewSingleLocationGroup.njk

* 'Add location group' form - with input validation
* Tests
* A few minor tweaks to other templates

VB-2431 Add a location group

---

server/services/incentiveGroupService.ts
server/services/locationGroupService.ts
server/services/prisonService.ts
server/services/sessionTemplateService.ts

Add log messages when items are created, deleted, activated or deactivated.

Log data change operations in services

---

server/constants/prisonerCategories.ts
server/data/visitSchedulerApiClient.test.ts
server/data/visitSchedulerApiClient.ts
server/data/visitSchedulerApiTypes.ts
server/routes/prisons/categoryGroups/addCategoryGroupController.test.ts
server/routes/prisons/categoryGroups/addCategoryGroupController.ts
server/routes/prisons/categoryGroups/categoryGroupsController.ts
server/routes/prisons/categoryGroups/index.ts
server/routes/prisons/categoryGroups/singleCategoryGroupController.ts
server/routes/testutils/testData.ts
server/services/categoryGroupService.test.ts
server/services/categoryGroupService.ts
server/views/pages/prisons/categoryGroups/addCategoryGroup.njk
server/views/pages/prisons/categoryGroups/viewCategoryGroups.njk
server/views/pages/prisons/categoryGroups/viewSingleCategoryGroup.njk

VB-2419, VB-2420 create, view and delete Category group

VB-2419, VB-2420 create, view and delete Category group

---

server/constants/prisonerCategories.ts
server/routes/prisons/categoryGroups/categoryGroupsController.ts
server/routes/prisons/categoryGroups/singleCategoryGroupController.ts
server/routes/prisons/incentiveGroups/incentiveGroupsController.ts
server/routes/prisons/incentiveGroups/singleIncentiveGroupController.ts
server/views/pages/prisons/categoryGroups/viewSingleCategoryGroup.njk
server/views/pages/prisons/incentiveGroups/viewSingleIncentiveGroup.njk

View the category group display text on all categories and all incentives and single category and single incentive page.

VB-2419 - view category groups and incentive level updates to show display text instead of code

---

integration_tests/e2e/prisons/addSessionTemplate.cy.ts
integration_tests/mockApis/visitScheduler.ts
integration_tests/pages/prisons/addSessionTemplatePage.ts
server/routes/prisons/sessionTemplates/addSessionTemplateController.test.ts
server/routes/prisons/sessionTemplates/addSessionTemplateController.ts
server/routes/prisons/sessionTemplates/index.ts
server/views/pages/prisons/sessionTemplates/addSessionTemplate.njk

Update session template, add form - category types

VB-2422   Update session template, add form - category types

---

assets/scss/local.scss
server/routes/prisons/categoryGroups/singleCategoryGroupController.ts
server/routes/prisons/incentiveGroups/singleIncentiveGroupController.ts
server/routes/prisons/locationGroups/singleLocationGroupController.ts
server/routes/prisons/sessionTemplates/singleSessionTemplateController.test.ts
server/views/pages/prisons/categoryGroups/viewSingleCategoryGroup.njk
server/views/pages/prisons/incentiveGroups/viewSingleIncentiveGroup.njk
server/views/pages/prisons/locationGroups/viewSingleLocationGroup.njk
server/views/pages/prisons/sessionTemplates/viewSingleSessionTemplate.njk

* Where group items are listed when viewing a session template, make these links to view the group item.
* Incorporate support for changing the back link on the group item views so they return to the correct place

View session template page - link items in category / incentive / location group lists

---

server/data/visitSchedulerApiClient.test.ts
server/routes/prisons/categoryGroups/singleCategoryGroupController.test.ts
server/routes/prisons/incentiveGroups/addIncentiveGroupController.test.ts
server/routes/prisons/incentiveGroups/singleIncentiveGroupController.test.ts
server/routes/prisons/locationGroups/singleLocationGroupController.test.ts
server/services/categoryGroupService.test.ts
server/services/incentiveGroupService.test.ts
server/services/locationGroupService.test.ts
server/services/locationGroupService.ts
server/services/sessionTemplateService.test.ts
server/services/sessionTemplateService.ts

Added basic service and data layer tests for incentive category and location groups
Added tests for the single and add controllers - including back links

Improve test coverage for category / group / incentive features

---

audit-ci.json
package-lock.json
package.json

* Update dependencies
* Temporarily ignore Cypress issue until fix released

Update dependencies 2023-08-25

---

cypress.config.ts
integration_tests/e2e/prisons/prisonStatus/prisonStatus.cy.ts
integration_tests/e2e/prisons/prisons.cy.ts
integration_tests/e2e/prisons/sessionTemplates/addSessionTemplate.cy.ts
integration_tests/e2e/prisons/sessionTemplates/deleteSessionTemplateFailure.cy.ts
integration_tests/e2e/prisons/sessionTemplates/deleteSessionTemplateSuccess.cy.ts
integration_tests/e2e/prisons/sessionTemplates/viewSessionTemplateStatus.cy.ts
integration_tests/mockApis/visitScheduler/categoryGroups.ts
integration_tests/mockApis/visitScheduler/incentiveGroups.ts
integration_tests/mockApis/visitScheduler/locationGroups.ts
integration_tests/mockApis/visitScheduler/prisons.ts
integration_tests/mockApis/visitScheduler/sessionTemplates.ts
integration_tests/pages/prisons/prisonStatus/prisonStatusPage.ts
integration_tests/pages/prisons/prisonsPage.ts
integration_tests/pages/prisons/sessionTemplates/addSessionTemplatePage.ts
integration_tests/pages/prisons/sessionTemplates/viewSessionTemplatePage.ts
integration_tests/pages/prisons/sessionTemplates/viewSessionTemplatesPage.ts

Use folder structure similar to that in the application code.

Restructure integration tests

---

integration_tests/e2e/prisons/incentiveGroups/viewIncentiveGroups.cy.ts
integration_tests/e2e/prisons/sessionTemplates/addSessionTemplate.cy.ts
integration_tests/mockApis/visitScheduler/categoryGroups.ts
integration_tests/mockApis/visitScheduler/incentiveGroups.ts
integration_tests/mockApis/visitScheduler/locationGroups.ts
integration_tests/pages/page.ts
integration_tests/pages/prisons/incentiveGroups/viewIncentiveGroupsPage.ts
integration_tests/pages/prisons/prisonStatus/prisonStatusPage.ts
integration_tests/pages/prisons/sessionTemplates/viewSessionTemplatePage.ts
integration_tests/pages/prisons/sessionTemplates/viewSessionTemplatesPage.ts
server/data/visitSchedulerApiClient.test.ts
server/data/visitSchedulerApiClient.ts
server/data/visitSchedulerApiTypes.ts
server/routes/prisons/incentiveGroups/addIncentiveGroupController.test.ts
server/routes/prisons/incentiveGroups/singleIncentiveGroupController.test.ts
server/routes/prisons/sessionTemplates/addSessionTemplateController.test.ts
server/routes/testutils/testData.ts
server/services/incentiveGroupService.test.ts
server/services/incentiveGroupService.ts
server/views/pages/prisons/incentiveGroups/viewIncentiveGroups.njk
server/views/pages/prisons/sessionTemplates/viewSessionTemplates.njk

Add integration test for:
* viewing a prison's incentive level groups
Also:
* remove some duplication by putting some re-used methods on top `Page` class
* made naming of some types / test data more consistent

VB-2708 Integration tests for incentive groups

---

cypress.config.ts
integration_tests/e2e/prisons/excludedDates/excludedDates.cy.ts
integration_tests/e2e/prisons/incentiveGroups/viewIncentiveGroups.cy.ts
integration_tests/e2e/prisons/locationGroups/viewLocationGroups.cy.ts
integration_tests/e2e/prisons/prisonStatus/prisonStatus.cy.ts
integration_tests/mockApis/visitScheduler/prisons.ts
integration_tests/mockApis/visitScheduler/visits.ts
integration_tests/pages/page.ts
integration_tests/pages/prisons/excludedDates/excludedDatesPage.ts
integration_tests/pages/prisons/incentiveGroups/viewIncentiveGroupsPage.ts
integration_tests/pages/prisons/locationGroups/viewLocationGroupsPage.ts
integration_tests/pages/prisons/prisonStatus/prisonStatusPage.ts
integration_tests/pages/prisons/sessionTemplates/viewSessionTemplatesPage.ts

* Add integration tests for prison excluded dates
* Improve checks for being on section pages

VB-2708 Add integration tests for excluded dates

---

server/@types/visit-scheduler-api.d.ts
server/routes/prisons/sessionTemplates/editSessionTemplateController.test.ts
server/routes/prisons/sessionTemplates/singleSessionTemplateController.ts
server/routes/testutils/testData.ts
server/views/pages/prisons/sessionTemplates/editSingleSessionTemplate.njk
server/views/pages/prisons/sessionTemplates/viewSingleSessionTemplate.njk

The visit stats endpoint now returns open and closed for visitsByDate instead of just a single count

Visit stats - visit count - type change

---

helm_deploy/hmpps-visits-internal-admin-ui/values.yaml

VB-3115 - set productId to DPS035 and also set serviceAccountName to visit-someone-in-prison.

VB-3115 - set productId to DPS035

---

helm_deploy/values-staging.yaml

Prison register doesn't have a staging environment so need to use its dev environment for our staging.

Fix prison register API for staging

---

bin/update-types.sh
package-lock.json
package.json
server/@types/booker-registry-api.d.ts
server/@types/prison-register-api.d.ts
server/@types/prisoner-contact-registry-api.d.ts
server/@types/visit-scheduler-api.d.ts

* Add `openapi-typescript` as a dev dependency so all devs using same version
* Update generated types files (from the module's v6 format to that generated by v7)

Update openapi-typescript and generated type definitions

---

package-lock.json
package.json
server/middleware/setUpWebSession.ts

Remove uuid dependency and use Node's crypto.randomUUID() (as advised on https://www.npmjs.com/package/uuid)

Remove 'uuid' dependency and replace with crypto.randomUUID()

---

package-lock.json
package.json
server/views/pages/prisons/categoryGroups/addCategoryGroup.njk
server/views/pages/prisons/excludedDates/viewExcludedDates.njk
server/views/pages/prisons/incentiveGroups/addIncentiveGroup.njk
server/views/pages/prisons/sessionTemplates/viewSessionTemplates.njk

Update to accommodate breaking change (https://github.com/ministryofjustice/moj-frontend/releases/tag/v3.0.0)

VB-4864 Update MoJ frontend to v3

---

integration_tests/pages/bookers/bookerDetails.ts
server/routes/bookers/booker/bookerDetailsController.test.ts
server/routes/bookers/booker/editPrisonerController.ts
server/routes/bookers/booker/index.ts
server/views/pages/bookers/booker/addPrisoner.njk
server/views/pages/bookers/booker/details.njk
server/views/pages/bookers/booker/editPrisoner.njk

Allow about prisoner's currently registered prison to be updates - e.g. if the prisoner has been transferred. (Temporary solution until there is a user journey and/or automation to support this.)

VB-4920 Allow updating of a prisoner's registered prison

---

server/views/pages/prisons/locationGroups/viewSingleLocationGroup.njk

Very small text change to fix duplicate header and make header hierarchy accurate.

minor text change to tidy headings on page

---

assets/scss/application.scss

Changes width to 1170 to bring in line with "Manage prison visits" and other DPS services

Updates page width 

---

integration_tests/pages/index.ts
logger.ts
server/routes/index.test.ts
server/utils/nunjucksSetup.ts
server/views/pages/bookers/booker/addPrisoner.njk
server/views/pages/bookers/booker/details.njk

Small update to improve naming of the service, and also change "Prisoner number" to "Prison number"

Updates to service name and prison number

---

server/views/pages/bookers/booker/details.njk

Fixed incorrect class in booker details page

Fixed incorrect class

---

server/@types/express/index.d.ts
server/constants/constants.ts
server/routes/bookers/booker/addPrisonerController.ts
server/routes/bookers/booker/addVisitorController.ts
server/routes/bookers/booker/bookerDetailsController.test.ts
server/routes/bookers/booker/bookerDetailsController.ts
server/routes/bookers/booker/editPrisonerController.ts
server/routes/bookers/booker/index.ts
server/routes/bookers/booker/prisonerStatusController.ts
server/routes/bookers/booker/visitorStatusController.ts
server/routes/bookers/bookerSearchController.test.ts
server/routes/bookers/bookerSearchController.ts
server/routes/prisons/supportedPrisonsController.ts
server/views/pages/bookers/booker/addPrisoner.njk
server/views/pages/bookers/booker/addVisitor.njk
server/views/pages/bookers/booker/details.njk
server/views/pages/bookers/booker/editPrisoner.njk

Simplify booker management by using booker reference in URLs rather than initially looking up booker and then storing in session.
Makes booker management pages all stateless and ensures the latest data is always being shown.

VB-5522 Booker management: use booker reference in URL instead of storing in session

---

server/@types/booker-registry-api.d.ts
server/@types/express/index.d.ts
server/data/bookerRegistryApiClient.test.ts
server/data/bookerRegistryApiClient.ts
server/data/bookerRegistryApiTypes.ts
server/routes/bookers/booker/editPrisonerController.ts
server/routes/testutils/appSetup.ts
server/services/bookerService.test.ts
server/services/bookerService.ts

* Use new endpoint for updating a prisoner's registered prison - and remove previous workaround for this
* (unrelated - tweak some types for `req.flash()`)

VB-5672 Use new endpoint to update a prisoner's registered prison

---

server/routes/bookers/booker/index.ts
server/routes/bookers/index.ts
server/routes/index.ts
server/routes/prisons/categoryGroups/index.ts
server/routes/prisons/configuration/index.ts
server/routes/prisons/excludedDates/index.ts
server/routes/prisons/incentiveGroups/index.ts
server/routes/prisons/index.ts
server/routes/prisons/locationGroups/index.ts
server/routes/prisons/sessionTemplates/index.ts

Remove wrappers around route handlers that are now unnecessary since upgrading to Express 5.

Clean up after Express 5 upgrade
