- server/views/pages/prisons/viewSessionTemplates.njk
- server/views/pages/prisons/viewSingleSessionTemplate.njk
* View visit session templates - display open / closed capacity as separate columns
* View single session template - show days as e.g. "Monday" instead of "MONDAY"
> VB-2320 Display open / closed capacity as separate columns

- server/utils/nunjucksSetup.test.ts
- server/utils/nunjucksSetup.ts
- server/views/pages/prisons/viewSessionTemplates.njk
Make more space in the session templates listing table by:
* removing the Visit room column (not useful info on this page; can be seen when viewing single session template page)
* reducing width of weekly frequency column by shortening label
-----
**BEFORE**
-----
-----
**AFTER**
-----
-----
> Tweak templates listing to give more space

- README.md
- docker-compose.yml
- server/services/prisonService.test.ts
- server/services/prisonService.ts
* add `docker-compose` config to enable Prison register to run locally (handy when dev Prison register is off outside 'standard' hours for power saving...)
* Update `prisonService` to return `'UNKNOWN'` rather than `undefined` if a prison name can't be found for a given prison code
> Add Prison Register to local Docker

- server/constants/sessionTemplatesFilterRanges.ts
- server/routes/prisons/sessionTemplates/addSessionTemplateController.ts
- server/views/pages/prisons/viewSessionTemplates.njk
Display the status for each session template on the page listing all session templates
Updated the filter name to current and future, as this is what we filter on
Added a test that start date is in the XXXX format
> Show session template status on prisons page

- package-lock.json
- package.json
Express includes `body-parser` as a dependency so no need to include it separately. (See https://expressjs.com/en/changelog/4x.html#4.16.0)
(Looks like `body-parser` was removed from the template app configuration, but not from `package.json` - https://github.com/ministryofjustice/hmpps-template-typescript/pull/22.)
> Remove unused dependency: 'body-parser'

- server/data/visitSchedulerApiClient.test.ts
- server/data/visitSchedulerApiClient.ts
- server/routes/prisons/locationGroups/index.ts
- server/routes/prisons/locationGroups/singleLocationGroupController.ts
- server/services/locationGroupService.ts
Added delete for Location groups at the service, data and route layers.
Currently doesn't remove from the table `permitted_session_location` but that's being worked on by the back end devs (No link to the entry in `session_location_group`
> VB-2409, add delete functionality to location group

- server/@types/express/index.d.ts
- server/routes/prisons/sessionTemplates/addSessionTemplateController.test.ts
- server/routes/prisons/sessionTemplates/addSessionTemplateController.ts
- server/routes/prisons/sessionTemplates/index.ts
- server/routes/prisons/sessionTemplates/singleSessionTemplateController.test.ts
- server/views/pages/prisons/sessionTemplates/viewSingleSessionTemplate.njk
Adds a 'Copy' button when viewing a single session template. This opens up the 'Add session template' form with values pre-populated and the name prefixed with `COPY -`.
This doesn't actually make a copy; it just pre-fills values to a new template that is similar to an existing one can be added without needing to re-enter all the data.
> VB-2469 'Copy' a session template

- cypress.config.ts
- integration_tests/e2e/prisons/viewSessionTemplateStatus.cy.ts
- integration_tests/mockApis/visitScheduler.ts
- server/routes/prisons/categoryGroups/addCategoryGroupController.ts
- server/routes/prisons/categoryGroups/singleCategoryGroupController.ts
- server/routes/prisons/excludedDates/excludedDatesController.ts
- server/routes/prisons/incentiveGroups/addIncentiveGroupController.ts
- server/routes/prisons/incentiveGroups/singleIncentiveGroupController.ts
- server/routes/prisons/locationGroups/addLocationGroupController.ts
- server/routes/prisons/locationGroups/singleLocationGroupController.ts
- server/routes/prisons/prisonStatus/prisonStatusController.test.ts
- server/routes/prisons/prisonStatus/prisonStatusController.ts
- server/routes/prisons/sessionTemplates/addSessionTemplateController.ts
- server/routes/prisons/sessionTemplates/singleSessionTemplateController.test.ts
- server/routes/prisons/sessionTemplates/singleSessionTemplateController.ts
- server/routes/prisons/supportedPrisonsController.test.ts
- server/routes/prisons/supportedPrisonsController.ts
- server/utils/utils.test.ts
- server/utils/utils.ts
Standardise handling of API errors to include error response code and - if present - `developerMessage` information. Utils function added (`responseErrorToFlashMessage`) to process response errors to be suitable to display in GOVUK Error Summary box. For example:
Also, made handling of activating/deactivating prisons and session templates consistent with way other API calls are used in route controllers.
> Standardise handling of API errors

- integration_tests/e2e/prisons/addSessionTemplate.cy.ts
- integration_tests/e2e/prisons/deleteSessionTemplateFailure.cy.ts
- integration_tests/e2e/prisons/deleteSessionTemplateSuccess.cy.ts
- integration_tests/e2e/prisons/viewSessionTemplateStatus.cy.ts
- integration_tests/mockApis/visitSchedulerMocks.ts
- server/data/visitSchedulerApiClient.test.ts
- server/data/visitSchedulerApiClient.ts
- server/data/visitSchedulerApiTypes.ts
- server/routes/prisons/sessionTemplates/editSessionTemplateController.test.ts
- server/routes/prisons/sessionTemplates/editSessionTemplateController.ts
- server/routes/prisons/sessionTemplates/singleSessionTemplateController.ts
- server/routes/testutils/testData.ts
- server/services/sessionTemplateService.test.ts
- server/services/sessionTemplateService.ts
- server/views/pages/prisons/sessionTemplates/editSingleSessionTemplate.njk
- server/views/pages/prisons/sessionTemplates/viewSingleSessionTemplate.njk
Display session template statistics on the view and edit single session template pages
Also display relevant information for each field on the edit session template page - so the user can make an informed decision
Changes to the stats API will be added under a separate PR when released
> VB-2589, add template stats to view and edit session template pages

- server/data/visitSchedulerApiTypes.ts
- server/routes/prisons/locationGroups/addLocationGroupController.test.ts
- server/routes/prisons/locationGroups/addLocationGroupController.ts
Send empty location levels as undefined, this then inserts them into the database as NULL - which is what the original sql scripts did.
This then makes the session template the location group is tied to work as expected
> VB-2698, location level codes bug fix

- integration_tests/e2e/prisons/prisonStatus/prisonStatus.cy.ts
- integration_tests/e2e/prisons/supportedPrisons.cy.ts
- integration_tests/mockApis/visitScheduler/sessionTemplates.ts
- integration_tests/pages/prisonPage.ts
- integration_tests/pages/prisons/SupportedPrisonsPage.ts
- integration_tests/pages/prisons/prisonStatus/prisonStatusPage.ts
- integration_tests/pages/prisons/sessionTemplates/addSessionTemplatePage.ts
- integration_tests/pages/prisons/sessionTemplates/viewSessionTemplatePage.ts
- integration_tests/pages/prisons/sessionTemplates/viewSessionTemplatesPage.ts
- server/views/components/subNavigation.njk
- server/views/pages/home.njk
- server/views/pages/prisons/categoryGroups/addCategoryGroup.njk
- server/views/pages/prisons/categoryGroups/viewCategoryGroups.njk
- server/views/pages/prisons/categoryGroups/viewSingleCategoryGroup.njk
- server/views/pages/prisons/excludedDates/viewExcludedDates.njk
- server/views/pages/prisons/incentiveGroups/addIncentiveGroup.njk
- server/views/pages/prisons/incentiveGroups/viewIncentiveGroups.njk
- server/views/pages/prisons/incentiveGroups/viewSingleIncentiveGroup.njk
- server/views/pages/prisons/locationGroups/addLocationGroup.njk
- server/views/pages/prisons/locationGroups/viewLocationGroups.njk
- server/views/pages/prisons/locationGroups/viewSingleLocationGroup.njk
- server/views/pages/prisons/prisons.njk
- server/views/pages/prisons/sessionTemplates/addSessionTemplate.njk
- server/views/pages/prisons/sessionTemplates/editSingleSessionTemplate.njk
- server/views/pages/prisons/sessionTemplates/viewSessionTemplates.njk
- server/views/pages/prisons/sessionTemplates/viewSingleSessionTemplate.njk
- server/views/pages/prisons/status/status.njk
- server/views/partials/layout.njk
* Remove duplication in template code by putting primary navigation in the `layout.njk` and using a macro for the sub-navigation
* Restructure integration test page classes to add a `PrisonPage` representing the common elements in `/prisons` pages (e.g. sub-nav sections). Deeper pages can extend this rather than the `Page` class.
> Refactor primary and sub-navigation

- integration_tests/e2e/prisons/categoryGroups/addCategoryGroup.cy.ts
- integration_tests/e2e/prisons/categoryGroups/viewCategoryGroups.cy.ts
- integration_tests/e2e/prisons/categoryGroups/viewSingleCategoryGroup.cy.ts
- integration_tests/e2e/prisons/configuration/prisonConfig.cy.ts
- integration_tests/e2e/prisons/excludedDates/excludedDates.cy.ts
- integration_tests/e2e/prisons/incentiveGroups/addIncentiveGroup.cy.ts
- integration_tests/e2e/prisons/incentiveGroups/viewIncentiveGroups.cy.ts
- integration_tests/e2e/prisons/incentiveGroups/viewSingleIncentiveGroup.cy.ts
- integration_tests/e2e/prisons/locationGroups/addLocationGroup.cy.ts
- integration_tests/e2e/prisons/locationGroups/viewLocationGroups.cy.ts
- integration_tests/e2e/prisons/locationGroups/viewSingleLocationGroup.cy.ts
- integration_tests/e2e/prisons/sessionTemplates/addSessionTemplate.cy.ts
- integration_tests/e2e/prisons/sessionTemplates/updateSessionTemplate.cy.ts
- integration_tests/e2e/prisons/sessionTemplates/viewSessionTemplates.cy.ts
- integration_tests/e2e/prisons/sessionTemplates/viewSingleSessionTemplate.cy.ts
- integration_tests/e2e/prisons/sessionTemplates/viewSingleSessionTemplateDelete.cy.ts
- integration_tests/e2e/prisons/sessionTemplates/viewSingleSessionTemplateStatus.cy.ts
- integration_tests/e2e/prisons/supportedPrisons.cy.ts
- integration_tests/mockApis/prisonRegister.ts
- server/@types/prison-register-api.d.ts
- server/@types/visit-scheduler-api.d.ts
- server/data/prisonRegisterApiClient.test.ts
- server/data/prisonRegisterApiClient.ts
- server/data/prisonRegisterApiTypes.ts
- server/routes/testutils/testData.ts
- server/services/prisonService.test.ts
- server/services/prisonService.ts
Use new endpoint that just returns prison code/name (`/prisons/names`) in place of the existing `/prisons` that returns a lot of unnecessary data. The list of names is still cached within the `PrisonService`.
Most of the changes are actually just updating variable names to be more appropriate.
> VB-3181 Use new 'prison names' Prison Register endpoint

- helm_deploy/hmpps-visits-internal-admin-ui/Chart.yaml
- helm_deploy/hmpps-visits-internal-admin-ui/values.yaml
This PR migrates the project to use groups of IPs in their allowlist.
By referring to groups to IP addresses, we can centralize the definition of groups of ip addresses.
If these lists require changing in the future, we can change the definition once and future deploys across all services will automatically include these new IPs.
1 allowlist(s) have been detected that can be migrated.
The effect of applying this PR is as follows:
- The following groups will be applied: `internal`
- The size of the allowlist defined in this file will change: `9 => 1 (8 removed)`
The new Group membership will result in the following IPs being added to your allowlist by applying this PR:
Merging this PR should not result in any additional IP addresses being added to the allowlist.
The following IPs have been …
> Migrating project to use groups in allowlist

- server/routes/prisons/configuration/prisonConfigController.ts
* Ensure consistent typing between `string` and `number` when form data is processed
* Ensure validation minimum values match the warning text (i.e. `1` instead of `0`)
> VB-3240 Fix booking window validation

- server/routes/bookers/booker/addVisitorController.ts
- server/routes/bookers/booker/bookerDetailsController.ts
- server/views/pages/bookers/booker/details.njk
When managing bookers and their configured prisoners/visitors, handle API errors from the contact registry by assuming an empty response and showing an info message with the error details.
If a prisoner has been released, for example, the `403` from the contact registry in this case otherwise prevents editing of the booker.
(n.b. no tests for this as test coverage for booker management as a whole coming in next PR!)
> VB-4330 Handle contact registry API errors

- integration_tests/e2e/bookers/bookerManagement.cy.ts
- integration_tests/mockApis/bookerRegistry.ts
- integration_tests/pages/bookers/addPrisoner.ts
- integration_tests/pages/bookers/bookerDetails.ts
- server/@types/booker-registry-api.d.ts
- server/@types/prison-register-api.d.ts
- server/@types/prisoner-contact-registry-api.d.ts
- server/@types/visit-scheduler-api.d.ts
- server/data/bookerRegistryApiClient.test.ts
- server/data/bookerRegistryApiClient.ts
- server/routes/bookers/booker/addPrisonerController.ts
- server/routes/bookers/booker/bookerDetailsController.test.ts
- server/routes/bookers/booker/bookerDetailsController.ts
- server/routes/bookers/booker/index.ts
- server/routes/testutils/testData.ts
- server/services/bookerService.test.ts
- server/services/bookerService.ts
- server/views/pages/bookers/booker/addPrisoner.njk
- server/views/pages/bookers/booker/details.njk
Update to reflect changes in the API which now require a prisoner **and** prison entering when adding a prisoner to a booker account.
To do this a drop-down select component with prison names has been added to the 'Add prisoner' page.
> VB-4920 Select prison when adding a prisoner to a booker

- integration_tests/e2e/bookers/bookerManagement.cy.ts
- integration_tests/mockApis/bookerRegistry.ts
- integration_tests/pages/bookers/addPrisoner.ts
- integration_tests/pages/bookers/bookerDetails.ts
- server/@types/booker-registry-api.d.ts
- server/@types/prison-register-api.d.ts
- server/@types/prisoner-contact-registry-api.d.ts
- server/@types/visit-scheduler-api.d.ts
- server/data/bookerRegistryApiClient.test.ts
- server/data/bookerRegistryApiClient.ts
- server/routes/bookers/booker/addPrisonerController.ts
- server/routes/bookers/booker/bookerDetailsController.test.ts
- server/routes/bookers/booker/bookerDetailsController.ts
- server/routes/bookers/booker/editPrisonerController.ts
- server/routes/bookers/booker/index.ts
- server/routes/testutils/testData.ts
- server/services/bookerService.test.ts
- server/services/bookerService.ts
- server/views/pages/bookers/booker/addPrisoner.njk
- server/views/pages/bookers/booker/details.njk
- server/views/pages/bookers/booker/editPrisoner.njk
Update to reflect changes in the API which now require a prisoner and prison entering when adding a prisoner to a booker account.
* To do this a drop-down select component with prison names has been added to the 'Add prisoner' page.
* Allow a prisoner's currently registered prison to be updated - e.g. if the prisoner has been transferred. (Temporary solution until there is a user journey and/or automation to support this.)
> VB-3340 Booker management: add/edit a prisoner's registered prison

- server/views/pages/prisons/categoryGroups/viewCategoryGroups.njk
- server/views/pages/prisons/configuration/addEditContactDetails.njk
- server/views/pages/prisons/configuration/config.njk
- server/views/pages/prisons/configuration/editBookingWindow.njk
- server/views/pages/prisons/configuration/editVisitorConfig.njk
- server/views/pages/prisons/incentiveGroups/addIncentiveGroup.njk
- server/views/pages/prisons/incentiveGroups/viewIncentiveGroups.njk
- server/views/pages/prisons/locationGroups/addLocationGroup.njk
- server/views/pages/prisons/locationGroups/editLocationGroup.njk
- server/views/pages/prisons/locationGroups/viewLocationGroups.njk
- server/views/pages/prisons/prisons.njk
- server/views/pages/prisons/sessionTemplates/viewSessionTemplates.njk
Use Nunjuck's `escape` filter where appropriate and for GOVUK macros, use `text` instead of `html` attribute where possible (to benefit from auto-escaping with the former).
> VB-4197 Fix escaping of user-entered data

- integration_tests/pages/prisons/sessionTemplates/addSessionTemplate.ts
- server/views/pages/prisons/sessionTemplates/addSessionTemplate.njk
Default "Visit room" input to be "Visits Hall" when creating a new visit session template.
> VB-5081 Add default room name for new session templates

- integration_tests/e2e/bookers/bookerManagement.cy.ts
- integration_tests/mockApis/prisonerContactRegistry.ts
- server/data/prisonerContactRegistryApiClient.test.ts
- server/data/prisonerContactRegistryApiClient.ts
- server/middleware/setUpCsrf.ts
- server/services/prisonerContactsService.test.ts
- server/services/prisonerContactsService.ts
- server/views/pages/bookers/booker/addVisitor.njk
* Move to Contact Registry API v2
* Adding visitors for a booker/prisoner: show visitors without a date of birth, but with **disabled** input so they cannot be added
> Booker management: show visitors without date of birth entered
